name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
        id: java
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Setup Bazelisk
        run: go get github.com/bazelbuild/bazelisk
      - uses: actions/checkout@v2
      - name: Run bazel-diff tests
        run: USE_BAZEL_VERSION=last_rc ~/go/bin/bazelisk test //test/...
