name: Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
        id: java
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Setup Bazelisk
        run: go get github.com/bazelbuild/bazelisk
      - uses: actions/checkout@v2
      - name: Run integration test
        run: ./integration/integration_test.sh -e
      - uses: actions/checkout@v2
        with:
          repository: tinder-maxwellelliott/bazel-diff-repro-1
          ref: wip_fix
          path: /tmp/ExternalTargetImpactTest
          fetch-depth: 0
      - name: Run External Target Impact test
        run: /tmp/ExternalTargetImpactTest/bazel-diff.sh
